Repository markets/awesome-ruby, pull requests merged in 2020-05, with the labels that each got.

#990 update repos links
  README.md
Labels: update

#989 remove outdated repos
  README.md
Labels: removal

#991 credit_card_validations repo moved to didww org
  README.md
Labels: update

#992 add holidays
  README.md
Labels: addition

#993 add stimulus_reflex gem
  README.md
Labels: addition

#994 Add cable_ready gem
  README.md
Labels: addition

#995 Update tabulo
  README.md
Labels: update

#799 Add ComfyBootstrapForm (Form Builder)
  README.md
Labels: addition

#982 add view_component
  README.md
Labels: addition

#939 Add que-scheduler
  README.md
Labels: addition
